language: php

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install dovecot-imapd dovecot-pop3d
  - sudo touch /etc/dovecot/local.conf
  - sudo chmod 777 /etc/dovecot/local.conf
  - sudo echo 'listen = *, [::]' >> /etc/dovecot/local.conf
  - sudo echo 'mail_location = maildir:/home/%u/Maildir' >> /etc/dovecot/local.conf
  - sudo echo 'disable_plaintext_auth = no' >> /etc/dovecot/local.conf
  - sudo echo 'mail_max_userip_connections = 10000' >> /etc/dovecot/local.conf
  - sudo service dovecot restart
  - sudo useradd testuser -m -s /bin/bash
  - echo "testuser:applesauce" | sudo chpasswd
  - sudo service dovecot stop
  - sudo mkdir -p /home/testuser/
  - sudo cp -Rp tests/resources/Maildir /home/testuser/
  - sudo ls -la /home/testuser/
  - sudo chown -R testuser:testuser /home/testuser/Maildir
  - sudo sudo /bin/bash tests/resources/dovecotSsl.sh
  - sudo service dovecot start
  - sudo service dovecot restart
  - sudo service dovecot status
  - sudo doveconf -n
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:1.0.0
  - travis_retry composer install --no-interaction --prefer-source
  - composer dump-autoload -o

script:
  - netstat -tuln | grep 143
  - netstat -tuln | grep 993
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - php: hhvm
